/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/isometric.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-9.18, 8.5, 9.18]}
        rotation={[1.22, -0.33, 0.73]}
        scale={[0.26, 0.26, 0.26]}
      >
        <OrthographicCamera
          makeDefault={false}
          far={1000}
          near={0.1}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[1.42, 1.13, -0.82]}>
        <pointLight
          intensity={2}
          decay={2}
          color="#e278ff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[1.11, 1.55, -0.38]} rotation={[2.17, 0.17, 0.2]}>
        <spotLight
          intensity={50}
          angle={Math.PI / 8}
          penumbra={0.15}
          decay={2}
          color="#f279ff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-0.03, 0.38, 0.08]} scale={[0.45, 0.45, 0.45]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={nodes.Plane_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.015"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[-0.52, 0.24, 0.56]}
        scale={[0.59, 0.59, 0.59]}
      />
      <group
        position={[1.14, 1.18, -0.58]}
        rotation={[0, Math.PI / 9, 0]}
        scale={[0.14, 0.14, 0.14]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_2.geometry}
          material={nodes.Plane006_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[1.11, 1.2, -0.65]}
        rotation={[0, Math.PI / 9, 0]}
        scale={[0.46, 0.45, 0.46]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[-0.03, 0.38, 0.08]}
        scale={[0.45, 0.45, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={nodes.Circle.material}
        position={[1.2, 0.61, 0.12]}
        scale={[0.38, 0.55, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
        position={[1.2, 0.61, 0.12]}
        scale={[0.38, 0.55, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[1.19, 1.15, -0.77]}
        scale={[0.59, 0.59, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[-0.11, 2.11, -1.61]}
        scale={[0.44, 0.45, 0.44]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={nodes.Plane006.material}
        position={[-0.03, 0.38, 0.08]}
        scale={[0.45, 0.45, 0.45]}
      />
      <group position={[-0.03, 0.38, 0.08]} scale={[0.45, 0.45, 0.45]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_1.geometry}
          material={nodes.Plane010_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_2.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-0.82, 2.94, -1.51]}
        scale={[0.45, 0.45, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[-0.11, 2.94, -1.39]}
        scale={[0.45, 0.45, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Material.017"]}
        position={[0.35, 2.97, -1.37]}
        scale={[0.45, 0.45, 0.45]}
      />
      <group
        position={[1.32, 1.47, -1.05]}
        rotation={[0, Math.PI / 9, -Math.PI / 2]}
        scale={[0.59, 0.59, 0.59]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={nodes.Plane014_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_2.geometry}
          material={nodes.Plane014_2.material}
        />
      </group>
      <group
        position={[1.4, 1.68, -0.39]}
        rotation={[1.57, 0.09, -1.51]}
        scale={[0.59, 0.59, 0.59]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_1.geometry}
          material={nodes.Plane015_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_2.geometry}
          material={nodes.Plane015_2.material}
        />
      </group>
      <group position={[1.36, 0.6, -0.83]} scale={[0.59, 0.59, 0.59]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_3.geometry}
          material={nodes.Plane015_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_4.geometry}
          material={nodes.Plane015_4.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
        position={[1.11, 1.18, -1.02]}
        scale={[0.45, 0.45, 0.45]}
      />
      <group
        position={[1.11, 1.19, -1.02]}
        rotation={[0, 0, 0.07]}
        scale={[0.46, 0.46, 0.45]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_1.geometry}
          material={nodes.Plane017_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_2.geometry}
          material={nodes.Plane017_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={nodes.Plane013.material}
        position={[1.36, 0.6, -0.83]}
        scale={[0.59, 0.59, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={nodes.Plane014.material}
        position={[1.36, 0.6, -0.83]}
        scale={[0.59, 0.59, 0.59]}
      />
      <group position={[1.28, 0.6, -0.32]} scale={[1.52, 1.52, 1.52]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021_1.geometry}
          material={nodes.Plane021_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021_2.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={nodes.Circle002.material}
        position={[-1.3, 0.61, -1.21]}
        scale={[0.26, 0.26, 0.26]}
      />
      <group position={[-1.3, 0.61, -1.21]} scale={[0.26, 0.26, 0.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_1.geometry}
          material={nodes.Circle003_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_2.geometry}
          material={nodes.Circle003_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus.geometry}
        material={nodes.Torus.material}
        position={[0.12, 2.92, -1.39]}
        scale={[0.88, 0.88, 0.88]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle004.geometry}
        material={nodes.Circle004.material}
        position={[1.55, 2.35, -0.96]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={nodes.Plane017.material}
        position={[1.3, 0.69, 1.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert.geometry}
        material={nodes.Vert.material}
        position={[1.19, 1.2, -0.68]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[1.3, 0.69, 1.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={nodes.Plane018.material}
        position={[0.38, 1.01, -0.76]}
        scale={[0.36, 0.36, 0.36]}
      />
      <group position={[0.38, 1.01, -0.76]} scale={[0.36, 0.36, 0.36]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={nodes.Plane004_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={nodes.Plane004_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={nodes.Plane020.material}
        position={[0.38, 1.01, -0.76]}
        scale={[1.1, 1.1, 1.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={nodes.Plane021.material}
        position={[0.41, 1.02, -0.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle005.geometry}
        material={nodes.Circle005.material}
        position={[0.38, 1.04, -0.76]}
        scale={[0.1, 0.1, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={nodes.Plane022.material}
        position={[0.38, 0.72, -0.76]}
        rotation={[1.66, 0, 0]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={nodes.Plane023.material}
        position={[-0.03, 0.38, 0.08]}
        scale={[0.45, 0.45, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006.geometry}
        material={nodes.Circle006.material}
        position={[0.38, 0.65, -0.76]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007.geometry}
        material={nodes.Circle007.material}
        position={[0.38, 0.66, -0.76]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={nodes.Plane024.material}
        position={[-0.43, 0.61, -1.28]}
        scale={[0.2, 0.2, 0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle008.geometry}
        material={nodes.Circle008.material}
        position={[1.01, 0.81, -0.32]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.5, 0.5, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials["Material.016"]}
        position={[-0.03, 0.38, 0.08]}
        scale={[0.45, 0.45, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={nodes.Plane026.material}
        position={[1.22, 0.85, -0.22]}
        scale={[0.1, 0.1, 0.1]}
      />
      <group position={[0.87, 2.07, -1.36]} scale={[0.1, 0.1, 0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle009_1.geometry}
          material={nodes.Circle009_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle009_2.geometry}
          material={nodes.Circle009_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={nodes.Plane027.material}
        position={[0.86, 2.07, -1.37]}
      />
      <group position={[1.1, 2.07, -1.37]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028_1.geometry}
          material={nodes.Plane028_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028_2.geometry}
          material={nodes.Plane028_2.material}
        />
      </group>
      <group position={[1.17, 2.08, -1.37]} rotation={[0, 0, -0.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029_1.geometry}
          material={nodes.Plane029_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029_2.geometry}
          material={nodes.Plane029_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={nodes.Plane030.material}
        position={[1.31, 2.07, -1.32]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <group position={[1.38, 2.07, -1.37]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031_1.geometry}
          material={nodes.Plane031_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031_2.geometry}
          material={nodes.Plane031_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={nodes.Plane032.material}
        position={[1.45, 2.07, -1.37]}
      />
      <group position={[1.27, 2.43, -1.37]} rotation={[0, 0, -0.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane034_1.geometry}
          material={nodes.Plane034_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane034_2.geometry}
          material={nodes.Plane034_2.material}
        />
      </group>
      <group position={[1.41, 2.42, -1.32]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_1.geometry}
          material={nodes.Plane035_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_2.geometry}
          material={nodes.Plane035_2.material}
        />
      </group>
      <group position={[1.48, 2.42, -1.32]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane036_1.geometry}
          material={nodes.Plane036_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane036_2.geometry}
          material={nodes.Plane036_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane038.geometry}
        material={nodes.Plane038.material}
        position={[-0.43, 1.16, -1.28]}
        scale={[0.05, 0.1, 0.1]}
      />
      <group position={[1.31, 0.77, 0.75]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane041_1.geometry}
          material={nodes.Plane041_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane041_2.geometry}
          material={nodes.Plane041_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane041_3.geometry}
          material={nodes.Plane041_3.material}
        />
      </group>
      <group position={[1.3, 1.9, 0.77]} scale={[0.1, 0.1, 0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010_1.geometry}
          material={nodes.Circle010_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010_2.geometry}
          material={nodes.Circle010_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={nodes.Plane033.material}
        position={[1.3, 2.12, 0.79]}
        scale={[0.03, 0.05, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane040.geometry}
        material={nodes.Plane040.material}
        position={[1.08, 1.18, -0.27]}
        scale={[0.1, 0.1, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane041.geometry}
        material={nodes.Plane041.material}
        position={[1.08, 1.18, -0.27]}
        rotation={[Math.PI, -1.22, Math.PI]}
        scale={[0.1, 0.1, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[1.1, 1.52, -0.33]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane042.geometry}
        material={nodes.Plane042.material}
        position={[1.27, 0.77, 1]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={[1.2, 1, 1.2]}
      />
      <group
        position={[1.17, 1.94, 1.09]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_3.geometry}
          material={nodes.Plane035_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_4.geometry}
          material={nodes.Plane035_4.material}
        />
      </group>
      <group
        position={[1.17, 2.01, 1.09]}
        rotation={[Math.PI, 0.26, -Math.PI / 2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_5.geometry}
          material={nodes.Plane035_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_6.geometry}
          material={nodes.Plane035_6.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane045.geometry}
        material={nodes.Plane045.material}
        position={[1.2, 1.5, 0.85]}
        rotation={[0, 0, -Math.PI / 9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane046.geometry}
        material={nodes.Plane046.material}
        position={[1.25, 1.6, 0.85]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane048.geometry}
        material={nodes.Plane048.material}
        position={[1.26, 1.6, 1.26]}
        rotation={[0, 0.83, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane047.geometry}
        material={nodes.Plane047.material}
        position={[1.22, 1.5, 1.3]}
        rotation={[0, 0.83, -Math.PI / 9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert002.geometry}
        material={nodes.Vert002.material}
        position={[1.08, 1.29, -0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane049.geometry}
        material={materials["Material.014"]}
        scale={[16.5, 16.5, 16.5]}
      />
    </group>
  );
}

useGLTF.preload("/isometric.glb");
