/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/isometric.glb");

  //Walls
  nodes.Plane_1.material.transparent = true;
  nodes.Plane_1.material.opacity = 0.7;
  // materials["Material.015"].transparent = true;
  // materials["Material.015"].opacity = 0.5;
  // materials["Material.015"].roughness = 1;
  materials["Material.015"].metalness = 0.8;

  //Mouse, Chair
  nodes.Cube.material.metalness = 1;

  //Streamer lights
  // nodes.Circle004.material.transparent = true;
  // nodes.Circle004.material.opacity = 0.2;
  // nodes.Circle004.material.emissive = 0xffffff;
  nodes.Circle004.material.emissiveIntensity = 3;
  nodes.Circle004.material.emissive = { r: 80, g: 180, b: 230 };

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-0.03491282, 0.37587047, 0.07781464]}
        scale={[0.45499998, 0.45499998, 0.45499998]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={nodes.Plane_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.015"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[-0.51830077, 0.23807734, 0.76474625]}
        scale={[0.59149998, 0.59149998, 0.64539212]}
      />
      <group
        position={[1.13900805, 1.18444514, -0.38220108]}
        rotation={[0, Math.PI / 9, 0]}
        scale={[0.1365, 0.1365, 0.1365]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_2.geometry}
          material={nodes.Plane006_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[1.11148262, 1.19533479, -0.4578265]}
        rotation={[0, Math.PI / 9, 0]}
        scale={[0.45500016, 0.45499998, 0.45500016]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[-0.03491282, 0.37587047, 0.07781464]}
        scale={[0.45499998, 0.45499998, 0.45499998]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={nodes.Circle.material}
        position={[1.20321071, 0.60661983, 0.34692907]}
        scale={[0.3822, 0.546, 0.3822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
        position={[1.20321071, 0.60661983, 0.34692907]}
        scale={[0.3822, 0.546, 0.3822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[1.19485426, 1.1475414, -0.68107432]}
        scale={[0.59149998, 0.59149998, 0.65224761]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[-0.10684356, 2.1122663, -1.61371553]}
        scale={[0.44364822, 0.45372224, 0.44364822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={nodes.Plane006.material}
        position={[-0.03491282, 0.42760134, 0.07781464]}
        scale={[0.45499998, 0.45499998, 0.45499998]}
      />
      <group
        position={[-0.03491282, 0.42760134, 0.07781464]}
        scale={[0.45499998, 0.45499998, 0.45499998]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_1.geometry}
          material={nodes.Plane010_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_2.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-0.81842208, 2.94332743, -1.51144266]}
        scale={[0.45499998, 0.45499998, 0.45499998]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[-0.10715508, 2.94332743, -1.38679528]}
        scale={[0.45499998, 0.45499998, 0.45499998]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Material.017"]}
        position={[0.34784505, 2.97310948, -1.36559415]}
        scale={[0.45499998, 0.45499998, 0.45499998]}
      />
      <group
        position={[1.31573987, 1.46535158, -1.04909897]}
        rotation={[-3e-8, Math.PI / 9, -Math.PI / 2]}
        scale={[0.59149998, 0.59150016, 0.59150016]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={nodes.Plane014_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_2.geometry}
          material={nodes.Plane014_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
        position={[1.11305702, 1.18445635, -0.82359725]}
        scale={[0.45499998, 0.45499998, 0.45499998]}
      />
      <group
        position={[1.11305702, 1.19219542, -0.82359725]}
        rotation={[0, 0, 0.07215365]}
        scale={[0.45500001, 0.45500001, 0.45499998]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_1.geometry}
          material={nodes.Plane017_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_2.geometry}
          material={nodes.Plane017_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={nodes.Plane013.material}
        position={[1.36335647, 0.60243756, -0.83167958]}
        scale={[0.59149998, 0.59149998, 0.59149998]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={nodes.Plane014.material}
        position={[1.36335647, 0.60243756, -0.83167958]}
        scale={[0.59149998, 0.59149998, 0.59149998]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={nodes.Plane015.material}
        position={[1.36335647, 0.60243756, -0.83167958]}
        scale={[0.59149998, 0.59149998, 0.59149998]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={nodes.Plane016.material}
        position={[1.2828573, 0.59903461, -0.1684317]}
        scale={[1.52100027, 1.52100027, 1.52100027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={nodes.Circle002.material}
        position={[-1.30444133, 0.60660374, -1.21249104]}
        scale={[0.25999999, 0.25999999, 0.25999999]}
      />
      <group
        position={[-1.30444133, 0.60660374, -1.21249104]}
        scale={[0.25999999, 0.25999999, 0.25999999]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_1.geometry}
          material={nodes.Circle003_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_2.geometry}
          material={nodes.Circle003_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus.geometry}
        material={nodes.Torus.material}
        position={[0.11955644, 2.92490411, -1.38574243]}
        scale={[0.87658787, 0.87658787, 0.87658787]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle004.geometry}
        material={nodes.Circle004.material}
        position={[1.55433273, 2.34622788, -0.95898074]}
        rotation={[Math.PI / 2, -3e-8, -Math.PI / 2]}
        scale={[0.19999999, 0.19999999, 0.19999999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={nodes.Plane017.material}
        position={[1.3022368, 0.68508279, 1.16065121]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert.geometry}
        material={nodes.Vert.material}
        position={[1.18531966, 1.19543636, -0.48470092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[1.30223703, 0.68508255, 1.16065121]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={nodes.Plane018.material}
        position={[0.37944126, 1.01315689, -0.68842381]}
        scale={[0.36000001, 0.36000001, 0.36000001]}
      />
      <group
        position={[0.37944126, 1.01315689, -0.68842381]}
        scale={[0.36000001, 0.36000001, 0.36000001]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={nodes.Plane004_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={nodes.Plane004_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={nodes.Plane020.material}
        position={[0.37944126, 1.01315677, -0.68842375]}
        scale={[1.10000002, 1.10000002, 1.10000002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={nodes.Plane021.material}
        position={[0.40826634, 1.01515543, -0.68842381]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle005.geometry}
        material={nodes.Circle005.material}
        position={[0.37944126, 1.03970981, -0.68842381]}
        scale={[0.10000002, 0.10000002, 0.10000002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={nodes.Plane022.material}
        position={[0.37944126, 0.71710312, -0.68271089]}
        rotation={[1.65806277, 0, 0]}
        scale={[0.19999999, 0.19999999, 0.19999999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={nodes.Plane023.material}
        position={[-0.03491282, 0.38310415, 0.07781464]}
        scale={[0.45044518, 0.45044518, 0.45044518]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006.geometry}
        material={nodes.Circle006.material}
        position={[0.37944126, 0.64790136, -0.68842393]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007.geometry}
        material={nodes.Circle007.material}
        position={[0.37944126, 0.6633808, -0.68842393]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={nodes.Plane024.material}
        position={[-0.43171215, 0.60662651, -1.28033257]}
        scale={[0.19999999, 0.19999999, 0.19999999]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle008.geometry}
        material={nodes.Circle008.material}
        position={[1.00694394, 0.81286156, -0.1684317]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.5, 0.5, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials["Material.016"]}
        position={[-0.03491282, 0.37587047, 0.07781464]}
        scale={[0.45499998, 0.45499998, 0.45499998]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={nodes.Plane026.material}
        position={[1.22026205, 0.84600174, -0.07061347]}
        scale={[0.10000002, 0.10000002, 0.10000002]}
      />
      <group
        position={[0.86807525, 2.06904602, -1.35732865]}
        scale={[0.10000002, 0.10000002, 0.10000002]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle009_1.geometry}
          material={nodes.Circle009_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle009_2.geometry}
          material={nodes.Circle009_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={nodes.Plane027.material}
        position={[0.86050826, 2.07049489, -1.36600542]}
      />
      <group position={[1.10048985, 2.06905293, -1.36546314]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028_1.geometry}
          material={nodes.Plane028_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028_2.geometry}
          material={nodes.Plane028_2.material}
        />
      </group>
      <group
        position={[1.16692352, 2.07634068, -1.36546314]}
        rotation={[0, 0, -0.26179941]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029_1.geometry}
          material={nodes.Plane029_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029_2.geometry}
          material={nodes.Plane029_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={nodes.Plane030.material}
        position={[1.30904305, 2.06905293, -1.32081926]}
        rotation={[Math.PI, -1.5e-7, Math.PI]}
      />
      <group position={[1.38285077, 2.06905293, -1.36546314]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031_1.geometry}
          material={nodes.Plane031_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031_2.geometry}
          material={nodes.Plane031_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={nodes.Plane032.material}
        position={[1.45285082, 2.06905293, -1.36546314]}
      />
      <group
        position={[1.26705754, 2.42927623, -1.36901653]}
        rotation={[0, 0, -0.26179941]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane034_1.geometry}
          material={nodes.Plane034_1.material}
          onClick={(e) => console.log(e)}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane034_2.geometry}
          material={nodes.Plane034_2.material}
        />
      </group>
      <group
        position={[1.40917706, 2.42198825, -1.32437265]}
        rotation={[Math.PI, -1.5e-7, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_1.geometry}
          material={nodes.Plane035_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_2.geometry}
          material={nodes.Plane035_2.material}
        />
      </group>
      <group
        position={[1.48401845, 2.42198825, -1.32301593]}
        rotation={[Math.PI, -1.5e-7, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane036_1.geometry}
          material={nodes.Plane036_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane036_2.geometry}
          material={nodes.Plane036_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane038.geometry}
        material={nodes.Plane038.material}
        position={[-0.43171215, 1.161919, -1.28033257]}
        scale={[0.05400001, 0.10000002, 0.10000002]}
      />
      <group position={[1.30787408, 0.77300102, 0.74968082]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane041_1.geometry}
          material={nodes.Plane041_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane041_2.geometry}
          material={nodes.Plane041_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane041_3.geometry}
          material={nodes.Plane041_3.material}
        />
      </group>
      <group
        position={[1.30188048, 1.90204024, 0.77364892]}
        scale={[0.10000002, 0.10000002, 0.10000002]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010_1.geometry}
          material={nodes.Circle010_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010_2.geometry}
          material={nodes.Circle010_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={nodes.Plane033.material}
        position={[1.29688466, 2.12334967, 0.78591603]}
        scale={[0.027, 0.05000001, 0.05000001]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane040.geometry}
        material={nodes.Plane040.material}
        position={[1.06358659, 1.18474579, -0.04261592]}
        scale={[0.10000002, 0.10000002, 0.10000002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane041.geometry}
        material={nodes.Plane041.material}
        position={[1.06358659, 1.18474579, -0.04261592]}
        rotation={[Math.PI, -1.22173067, Math.PI]}
        scale={[0.10000002, 0.10000002, 0.10000002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[1.10158753, 1.5345273, -0.11705822]}
        scale={[0.02909137, 0.02909137, 0.02909137]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane042.geometry}
        material={nodes.Plane042.material}
        position={[1.35226607, 0.77300102, 0.99968082]}
        rotation={[0, -1.34270963, 0]}
        scale={[1.19999993, 0.99528331, 1.19999993]}
      />
      <group
        position={[1.16507292, 1.93846476, 1.08916485]}
        rotation={[Math.PI, 4e-8, -Math.PI / 2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_3.geometry}
          material={nodes.Plane035_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_4.geometry}
          material={nodes.Plane035_4.material}
        />
      </group>
      <group
        position={[1.16507292, 2.01304793, 1.08916485]}
        rotation={[Math.PI, 0.26179967, -Math.PI / 2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_5.geometry}
          material={nodes.Plane035_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035_6.geometry}
          material={nodes.Plane035_6.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane045.geometry}
        material={nodes.Plane045.material}
        position={[1.19751847, 1.50171995, 0.84969425]}
        rotation={[0, 0, -Math.PI / 9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane046.geometry}
        material={nodes.Plane046.material}
        position={[1.2532438, 1.60337758, 0.84969419]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane048.geometry}
        material={nodes.Plane048.material}
        position={[1.27112842, 1.60337758, 1.28215766]}
        rotation={[0, 0.02925516, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane047.geometry}
        material={nodes.Plane047.material}
        position={[1.21542668, 1.50171995, 1.28378773]}
        rotation={[1e-8, 0.02925517, -Math.PI / 9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert002.geometry}
        material={nodes.Vert002.material}
        position={[1.06358659, 1.28671014, -0.04261589]}
      />
      <group
        position={[1.38411295, 1.46535158, -0.11944152]}
        rotation={[1e-8, -0.20294445, -Math.PI / 2]}
        scale={[0.59149998, 0.59150016, 0.59150016]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={nodes.Plane001_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={nodes.Plane001_2.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/isometric.glb");
